---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - access_control/tests/**/*
      - models/tests/**/*
      - tests/**/*
      - utils_control/tests/**/*
    config:
      languages:
        ruby:
        javascript:
        python:
          mass_threshold: 50
        php:
  fixme:
    enabled: true
  radon:
    enabled: true
    exclude_fingerprints:
    - 7bf39e90b7b6c666bc92955cbfd27432
    - 5f9aaf4e3539a3d5f7012c221397ceac
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "models/proxy_model.py"
- "utils/pbkdf2_hmac.py"
