language: python

python:
  - "2.7"

services:
  - mysql

env:
  - DB=sqlite
  - DB=mysql WOODBOX_DATABASE_URI="mysql+mysqldb://travis@localhost/woodbox_test"

before_install:
  - pip install codecov

install: "pip install -r REQUIREMENTS.txt"

before_script:
  - sh -c "if [ $DB = mysql ]; then mysql -e 'create database IF NOT EXISTS woodbox_test'; fi"

script:
  - nose2 -t .. --with-coverage

after_success:
  - codecov
